# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Mohammad R Nateghi
title: IT consultant / Executive / Freelancer
email: Nateghi7@gmail.com
website: https://nateghi7.github.io/CV/

# Social links
twitter_username: Nateghi7
github_username:  Nateghi7
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: 
linkedin_username: 
# pinterest_username: jekyll
youtube_username: 
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am Moe, A passionate person about computers and technology as long as I can remember. I have had different positions in IT Industry and been on a wild journey of “How this tech works?” and “What are the possible solutions?” which led me to face different aspect of the industry and relative problem-solving skills. It all started from Helpdesk/Troubleshooting to Hardware Expert, Mining Executive,Content Manager and Auditor into Freelancing/Consulting. I do have an enthusiastic approach to find the new skillsets which demand is going to flourish and I would like to team up with the same-minded individuals to define new solutions.

  I am most skilled in: <mark>computer networks</mark> and <mark>Bitcoin, Blockchain and Cryptocurrencies</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Basketball
   - Gaming
   - Financial Markets
   - Sustainable Future

# Footer
footer_show_references: false
# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
